cart/urls.py
#coding=utf-8

from django.contrib import admin
from django.urls import path, re_path, include
import goods
from cart import views
from netshop.settings import DEBUG, MEDIA_ROOT

app_name = 'cart'

urlpatterns = [
    path('addcart/', views.AddCartView.as_view(), name='addcart'),
    path('gocart/', views.GoCartView.as_view(), name='gocart'),


]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

goods/urls.py
#coding=utf-8

from django.contrib import admin
from django.urls import path, re_path, include
import goods
from goods import views
from netshop.settings import DEBUG, MEDIA_ROOT

app_name = 'goods'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:cid>/', views.IndexView.as_view(), name='index'),
    path('category/<int:cid>/<int:pagenum>/', views.IndexView.as_view(), name='index'),
    path('goodsdetails/<int:goodsid>/', views.DetailView.as_view(), name='details'),
]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

netshop/urls.py
#coding=utf-8
"""netshop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

import goods
from netshop.settings import DEBUG, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls')),
    path('user/', include('userapp.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('test/', include('testapp.urls')),
    path('captcha/', include('captcha.urls')),      # 验证码路由配置
]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

goods/models.py
# Create your models here.
import collections

from django.db import models


class Category(models.Model):
    cname = models.CharField(max_length=10)

    def __str__(self):
        return 'Category:%s' % self.cname


class Goods(models.Model):
    gname = models.CharField(max_length=100)
    gdesc = models.CharField(max_length=100)
    oldprice = models.DecimalField(max_digits=5, decimal_places=2)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, db_column='category_id')

    def __str__(self):
        return 'Goods:%s' % self.gname

    def getGImg(self):
        return self.inventory_set.first().color.colorurl  # 获取该商品库存的第一个对象

    # 获取商品所有颜色对象
    def getColor(self):
        colorlist = []
        for inventory in self.inventory_set.all():
            color = inventory.color
            if color not in colorlist:
                colorlist.append(color)
        return colorlist

    def getSize(self):
        sizelist = []
        for inventory in self.inventory_set.all():
            size = inventory.size
            if size not in sizelist:
                sizelist.append(size)
        return sizelist

    def getGoodsDetial(self):
        gdlist = collections.OrderedDict()     # 创建一个有序字典（key为详情名称；value为图片列表）
        for goodsdetal in self.goodsdetail_set.all():
            gdname = goodsdetal.goodsDetailName.gdname
            if not gdlist.get(gdname):
                gdlist[gdname] = [goodsdetal.gdurl]
            else:
                gdlist[gdname].append(goodsdetal.gdurl)
        return gdlist


class Color(models.Model):
    colorname = models.CharField(max_length=10)
    colorurl = models.ImageField(upload_to='color/')


class Size(models.Model):
    sname = models.CharField(max_length=10)

    def __str__(self):
        return 'Size:%s' % self.sname


class Inventory(models.Model):
    count = models.IntegerField()
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)


class GoodsDetailName(models.Model):
    gdname = models.CharField(max_length=30)

    def __str__(self):
        return 'GoodsDetailName:%s' % self.gdname


class GoodsDetail(models.Model):
    gdurl = models.ImageField(upload_to='')
    goodsDetailName = models.ForeignKey(GoodsDetailName, on_delete=models.CASCADE, db_column='gdname_id')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

goods/views.py
import math

from django.core.paginator import Paginator
from django.shortcuts import render
# Create your views here.
from django.views.generic.base import View

from goods.models import *


class IndexView(View):
    def get(self, request, cid=2, pagenum=1):
        categories = Category.objects.all()
        goodslist = Goods.objects.filter(category_id=cid).order_by('-id')

        # 分页
        paginator = Paginator(goodslist, 8)
        page = paginator.page(pagenum)
        # 每页开始
        begin = (pagenum - int(math.ceil(10.0 / 2)))
        if begin < 1:
            begin = 1
        # 每页结束页
        end = begin + 9
        if end > paginator.num_pages:
            end = paginator.num_pages
        if end <= 10:
            begin = 1
        else:
            begin = end - 9
        pagelist = range(begin, end + 1)
        return render(request, 'index.html', locals())


# 装饰器: 获取历史浏览商品信息
def recommend_view(func):
    def wrapper(DetailView, request, goodsid, *args, **kwargs):
        goodsid = str(goodsid)
        # 获取存放在cookie中的goodsid
        cookie_str = request.COOKIES.get('recommend', '')
        # goods_id_list save all of goodsid
        goods_id_list = cookie_str.split()
        # 最终获取推荐的商品
        goodsObjectList = [Goods.objects.get(id=gsid) for gsid in goods_id_list if
                           gsid != goodsid and Goods.objects.get(id=gsid).category_id == Goods.objects.get(
                               pk=goodsid).category_id][:4]
        # 将goodsObjectList传递给get方法
        response = func(DetailView, request, goodsid, goodsObjectList, *args, **kwargs)
        # 判断goodsid是否存在于列表中，设置最新的goodsid
        if goodsid in goods_id_list:
            goods_id_list.remove(goodsid)
        goods_id_list.insert(0, goodsid)
        # 将goods_id_list中的数据存放到Cookie
        response.set_cookie('recommend', ' '.join(goods_id_list), max_age=3 * 24 * 60 * 60)
        return response

    return wrapper


class DetailView(View):
    @recommend_view
    def get(self, request, goodsid, recommendlist=[]):
        goods = Goods.objects.get(pk=goodsid)
        return render(request, 'goodsdetails.html', locals())

goods/templates/goodsdetails.html
{% extends 'base.html' %}
{% block title %}
    商品详情
{% endblock %}
{% block main %}
    <div class="detail-body" goodsid="25">
        <!-- 面包屑 -->
        <div class="bread">
            <ul class="bread-content">
                <li class="bread-item">
                    <a href="/">首页</a>&gt;
                </li>

                <li class="bread-item">
                    <a href="/category/{{ goods.category_id }}">{{ goods.category.cname }}</a>&gt;
                </li>

                <li class="bread-item">
                    <a href="javascript:void(0);">{{ goods.gname }}</a>
                </li>
            </ul>
        </div>

        <!-- detail-content -->
        <div class="detail-content">
            <div class="detail-con-left">
                <img id="rightimg" src="{{ goods.getGImg }}">
            </div>
            <div class="detail-con-right">
                <h3>{{ goods.gdesc }}</h3>
                <div class="price">
                    <i>￥</i>
                    <p>{{ goods.price }}</p>
                    <s>￥{{ goods.oldprice }}</s>
                </div>

                <div class="line"></div>
                <div class="color">
                    <p class="p-item">颜色：</p>
                    <ul class="MinImgList">
                        {% for color in goods.getColor %}

                            <li class="MinImg {% if forloop.first %}active{% endif %}" colorid="{{ color.id }}">
                                <img src="{{ color.colorurl }}" width="30px" height="30px">
                            </li>

                        {% endfor %}


                    </ul>
                </div>
                <div class="size">
                    <p class="p-item">
                        尺码：
                    </p>
                    <ul class="size-list">
                        {% for size in goods.getSize %}
                            <li sizeid="{{ size.id }}"
                                class="size-item {% if forloop.first %}active{% endif %}">{{ size.sname }}</li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="num">
                    <p class="p-item">
                        数量：
                    </p>
                    <div class="jian">-</div>
                    <input type="number" name="" value="1">
                    <div class="jia">+</div>
                </div>
                <form action="{% url 'cart:addcart' %}" method="post">
                    {% csrf_token %}
                    <input name="colorid" type="hidden">
                    <input name="goodsid" type="hidden" value="{{ goodsid }}">
                    <input name="sizeid" type="hidden">
                    <input name="count" type="hidden">
                    <input name="flag" value="add" type="hidden">
                     {% csrf_token %}
                    <button class="male" onclick="goCart()">单独购买</button>
                </form>
            </div>
            <div class="detail-con-nav">
                <ul class="detail-nav">
                    <li class="active nav-item "><a href="{% url 'goods:details' goodsid %}">商品详情</a></li>
                    <li class="nav-item"><a href="{% url 'goods:details' goodsid %}">物流与售后</a></li>
                    <li class="nav-item"><a href="{% url 'goods:details' goodsid %}">消费保障</a></li>
                    <li class="nav-item"><a href="{% url 'goods:details' goodsid %}">手机购买</a></li>
                </ul>
            </div>
            <div class="sub-nav">
                <ul class="subNav">
                    {% for gd in goods.getGoodsDetial %}
                        <li><a href="/goodsid={{ goods.id }}#">{{ gd }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="zhanshi">

                {% for gdname,gdurlList in goods.getGoodsDetial.items %}


                    <div class="zhanshi-model">
                        <p>{{ gdname }}</p>
                        <div class="line"></div>
                        {% for gdurl in gdurlList %}
                            <img src="{{ gdurl }}" alt="">
                        {% endfor %}

                    </div>

                {% endfor %}


            </div>
        </div>
    </div>


    <div class="goods-model" style="margin-right: -18px;text-align: center">
        <img src="./首页_files/recommend.png" style="position: relative;left: -10px;top: 10px">

        <div class="goods-content">

            {% for good in recommendlist %}
                <div class="good">
                    <a href="{% url 'goods:details' goodsid %}">
                        <img src="{{ good.getColor.0.colorurl }}" width="285px" height="285px">
                        <p class="name">{{ good.gname }}</p>
                        <div class="price">
                            <i>￥</i>
                            <p class="big">{{ good.price }}</p>
                            <s>￥{{ good.price }}</s>
                        </div>
                        <div class="sale">
                            特卖
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

{% block footerjs %}





    <script>
        $('.MinImg').click(function () {
            $('.MinImg').removeClass('active')
            $(this).addClass('active')
            $('#rightimg').attr('src', $(this).children('img').attr('src'))
        })
        $('.size-item').click(function () {
            $('.size-item').removeClass('active')
            $(this).addClass('active')
        })
        $('.jian').click(function () {

            num_text_view = $('.num').children('input[type="number"]')
            val = $(num_text_view).val()
            if (val <= 1) return
            $(num_text_view).val(val - 1)
        })
        $('.jia').click(function () {
            <!--发给服务器问一下这个商品(商品+颜色+尺寸)还有没有货-->
            num_text_view = $('.num').children('input[type="number"]')
            val = eval($(num_text_view).val())
            if (val >= 60) return
            $(num_text_view).val(val + 1)

        })
        //单独购买
        //<input type="hidden" name="colorid" value=""/>
        function goCart() {
            $('form').children('input[name="colorid"]').val($('.MinImg.active').attr('colorid'))
            $('form').children('input[name="sizeid"]').val($('.size-item.active').attr('sizeid'))
            $('form').children('input[name="count"]').val($('.num').children('input[type="number"]').val())
        }
    </script>




{% endblock %}

goods/templates/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block headerjs %}
    <style>
        .curpage{
            font-size: 28px;
            color: green;
        }
    </style>
{% endblock %}
{% block main %}

    <div class="classes">
        <ul class="classes-items">

            {% for category in categories %}
                {% if category.id == cid %}
                    <li class="items active"><a
                            href="{% url 'goods:index' category.id %}">{{ category.cname }}</a>
                        {% else %}
                    <li class="items"><a
                            href="{% url 'goods:index' category.id %}">{{ category.cname }}</a>
                    </li>
                {% endif %}

            {% endfor %}


        </ul>
    </div>

    <div class="goods-model">
        <div class="goods-content">
            {% for goods in page.object_list %}
                <div class="good">
                    <a href="{% url 'goods:details' goods.id %}">
                        <img src="{{ goods.getGImg }}" width="285px" height="285px">
                        <p class="name">{{ goods.gname }}</p>
                        <div class="price">
                            <i>￥</i>
                            <p class="big">{{ goods.price }}</p>
                            <s>￥{{ goods.oldprice }}</s>
                        </div>
                        <div class="sale">
                            特卖
                        </div>
                    </a>
                </div>
            {% endfor %}


        </div>
    </div>

    <div id="pager" style="text-align: center; font-size: 16px; overflow: hidden; margin-top: 10px;">
        {% if page.has_previous %}
            <a href="{% url 'goods:index' goodslist.1.category.id page.previous_page_number %}"
               style="display: inline-block; padding: 5px; margin: 5px;">上一页</a>
        {% endif %}
        {% for num in pagelist %}
            {% if pagenum == num %}
                <span class="curpage">{{ num }}</span>
            {% else %}
                <a href="{% url 'goods:index' goodslist.1.category.id  num %}">{{ num }}</a>
            {% endif %}

        {% endfor %}

        {% if page.has_next %}
            <a href="{% url 'goods:index' goodslist.1.category.id page.next_page_number %}"
               style="display: inline-block; padding: 5px; margin: 5px;">下一页</a>
        {% endif %}


    </div>


{% endblock %}


{% block footerjs %}

    <script>
        $('#pager').css({'text-align': 'center', 'font-size': '16px', 'overflow': 'hidden', 'margin-top': '10px'})
        $('#pager a').css({'display': 'inline-block', 'padding': '5px', 'margin': '5px'})

    </script>

{% endblock %}