cart/urls.py
#coding=utf-8

from django.contrib import admin
from django.urls import path, re_path, include
import goods
from cart import views
from netshop.settings import DEBUG, MEDIA_ROOT

app_name = 'cart'

urlpatterns = [
    path('addcart/', views.AddCartView.as_view(), name='addcart'),
    path('gocart/', views.GoCartView.as_view(), name='gocart'),


]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

netshop/urls.py
#coding=utf-8
"""netshop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

import goods
from netshop.settings import DEBUG, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls')),
    path('user/', include('userapp.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('test/', include('testapp.urls')),
    path('captcha/', include('captcha.urls')),      # 验证码路由配置
]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

userapp/urls.py
#coding=utf-8

from django.contrib import admin
from django.urls import path, re_path, include
import goods
from userapp import views
from netshop.settings import DEBUG, MEDIA_ROOT

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('checkuname/', views.CheckUsername.as_view(), name='checkuname'),
    path('center/', views.CenterView.as_view(), name='center'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('refresh/', views.refresh, name='refresh'),       # 刷新验证码
    path('address/', views.AddressView.as_view(), name='address'),
    path('loadarea/', views.LoadAreaView.as_view(), name='loadarea'),
    path('setdefaultaddr/', views.SetDefaultAddrView.as_view(), name='setdefaultaddr'),
    path('deleteaddr/', views.DeleteAddrView.as_view(), name='deleteaddr'),

]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

userapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


# 样板 》 WejoyArea
class Area(models.Model):
    areaid = models.IntegerField(primary_key=True)
    areaname = models.CharField(max_length=50)
    parentid = models.IntegerField()
    arealevel = models.IntegerField()
    status = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'area'




class Address(models.Model):
    aname = models.CharField(max_length=30)
    aphone = models.CharField(max_length=11)
    addr = models.CharField(max_length=100)
    isdefault = models.BooleanField(default=False)
    userinfo = models.ForeignKey('UserInfo', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'userapp_address'


class UserInfo(models.Model):
    uname = models.CharField(max_length=100)
    pwd = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'userapp_userinfo'


class Areas(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='name', max_length=40, blank=True, null=True)  # Field name made lowercase.
    pid = models.ForeignKey('self', models.DO_NOTHING, db_column='pid', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'areas'

userapp/forms.py
# -*- coding = utf-8 -*-
# @Time :
# @ Author : Yeeero
# @File : forms.by
# @Software : PyCharm

# 登录验证，验证码
from captcha.fields import CaptchaField
from django import forms


class LoginForm(forms.Form):
    uname = forms.CharField(min_length=6, required=True)
    pwd = forms.CharField(required=True, min_length=4, error_messages={
        'required': '密码必须填写',
        'min_length': '密码不能小于4位',
    })
    # 验证码使用， error_massage修改错误提示信息
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})

userapp/views.py
from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
# Create your views here.
from django.views.generic.base import View

from userapp.forms import LoginForm
from userapp.models import *


# 装饰器，用户登录状态验证,未登录用户跳转到登录页面
def checkLogin(params=None):        # param => next, 登录后需要跳转的url
    def inner(func):
        def wrapper(obj, request, *args, **kwargs):
            print(params)
            if request.session.get('user'):
                return func(obj, request, *args, **kwargs)
            return redirect('/user/login/?next={}'.format(params))
        return wrapper
    return inner



class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        username = request.POST.get('uname')
        password = request.POST.get('pwd')
        try:
            user = UserInfo.objects.create(uname=username, pwd=password)
        except Exception:
            return redirect(reverse('user:register'))
        request.session['user'] = user
        return redirect(reverse('user:center'))


# Ajax 验证注册用户
class CheckUsername(View):
    def get(self, request):
        uname = request.GET.get('uname')
        if UserInfo.objects.filter(uname=uname):
            return JsonResponse({'flag': True})
        else:
            return {'flag': False}


class CenterView(View):
    @checkLogin
    def get(self, request):
        return render(request, 'center.html')


class LogoutView(View):
    def get(self, request):
        if 'user' in request.session:
            del request.session['user']
        return redirect(reverse('goods:index'))

    def post(self, request):
        # 删除session中登录用户信息
        if 'user' in request.session:
            del request.session['user']

        return JsonResponse({'delflag': True})


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        next = request.GET.get('next')  # 获取跳转页面的url
        print('----get---->next=', next)
        return render(request, 'login.html', locals())

    def post(self, request):
        form = LoginForm()
        # print(request.POST)
        validata = LoginForm(request.POST)
        print('validata = ', validata.errors)
        print('---->', validata.is_valid())
        if validata.errors:
            return render(request, 'login.html', locals())
        print('-' * 30)
        uname = request.POST.get('uname')
        pwd = request.POST.get('pwd')
        next = request.POST.get('next')  # 获取跳转页面的url
        print('next =', next)
        print('pwd = ', pwd)
        userlist = UserInfo.objects.filter(uname=uname, pwd=pwd)
        cleanData = validata.cleaned_data
        if userlist:
            request.session['user'] = userlist[0]
            try:
                return redirect(next)
            except:
                return redirect('user:center')
        else:
            return render(request, 'login.html', {'msg': '用户不存在或密码不正确', 'form': form})


# 刷新验证码
def refresh(request):
    form = LoginForm()
    return render(request, 'login.html', context=locals())


class AddressView(View):
    @checkLogin
    def get(self, request):
        user = request.session.get('user')
        addresslist = Address.objects.filter(userinfo=user)
        return render(request, 'address.html', locals())

    def post(self, request):
        aname = request.POST.get('aname')
        aphone = request.POST.get('aphone')
        addr = request.POST.get('addr')
        user = request.session.get('user')
        print(aname, '-', aphone, '-', addr)
        address = Address.objects.create(aname=aname, aphone=aphone, addr=addr, userinfo=user,
                               isdefault=(lambda count: True if count == 0 else False)(user.address_set.all().count()))
        return render(request, 'address.html', locals())


class LoadAreaView(View):
    def get(self, request):
        print('---' * 10)
        pid = request.GET.get('pid', 0)
        pid = int(pid)
        # 根据pid查询区划信息
        areas = Areas.objects.filter(pid=pid)
        # 序列化
        jarealist = serialize('json', areas)
        return JsonResponse({'jarealist': jarealist})


class SetDefaultAddrView(View):
    def get(self, request):
        print('-------setdefaultaddr-------')
        user = request.session.get('user')
        data = request.GET.dict()
        print(request.GET.dict())
        addresslist = Address.objects.filter(userinfo=user)
        for address in addresslist:
            address.isdefault = False
            address.save()
        address2 = Address.objects.get(userinfo=user, **data)
        address2.isdefault = True
        address2.save()
        return JsonResponse({"msg": True})


class DeleteAddrView(View):
    def get(self, request):
        data = request.GET.dict()
        user = request.session.get('user')
        address = Address.objects.get(userinfo=user, **data)
        address.delete()
        return JsonResponse({"msg": 'delete'})

userapp/templates/address.html
{% extends 'base.html' %}

{% block title %}地址管理{% endblock %}



{% block headerjs %}


    <link href="/static/assets/css/admin.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/css/amazeui.css" rel="stylesheet" type="text/css">

    <link href="/static/assets/css/personal.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/css/addstyle.css" rel="stylesheet" type="text/css">
    <script src="/static/assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/assets/js/amazeui.js"></script>



    <script>
        $(function () {
            loadProvince();
        });


        function loadProvince() {
            loadArea('province', 0, loadCity);
        }

        function loadCity() {
            loadArea('city', $('#province').val(), loadTown);
        }

        function loadTown() {
            loadArea('town', $('#city').val());
        }

        function loadArea(cytpe, pid, nextLoad) {
            $('#' + cytpe).empty()
            $.get('/user/loadarea/', {'pid': pid}, function (result) {
                console.log(result.jarealist);
                var arealist = JSON.parse(result.jarealist);

                // 遍历数组
                for (var i = 0; i < arealist.length; i++) {
                    var area = arealist[i];
                    $('#' + cytpe).append("<option value='" + area.pk + "'>" + area.fields.name + "</option>");
                }

                //判断是否需要加载下一级菜单
                if (nextLoad != null) {
                    nextLoad();
                }
            });
        }


    </script>

{% endblock %}

{% block main %}

    {% csrf_token %}
    <div class="Bott">
        <div class="wrapper clearfix" style="margin: 0 auto">
            <div class="zuo fl" style="margin-left: 100px">
                <h3>
                    <a href="/"><img src="/static/tx.png"></a>
                    <p class="clearfix"><span class="fl">[{{ suser.uname }}]</span><span class="fr logout">[退出登录]</span>
                    </p>
                </h3>
                <div>
                    <ul>
                        <li><a href="http://127.0.0.1:8000/user/usercenter/#">我的订单</a></li>
                    </ul>
                    <ul>
                        <li><a href="/user/address/">地址管理</a></li>
                    </ul>
                    <ul>
                        <li><a href="/">回到首页</a></li>
                    </ul>

                </div>
            </div>
            <div class="main-wrap you fl">

                <div class="user-address">
                    <!--标题 -->
                    <div class="am-cf am-padding">
                        <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">地址管理</strong> / <small>Address&nbsp;list</small>
                        </div>
                    </div>
                    <hr>
                    <ul class="am-avg-sm-1 am-avg-md-3 am-thumbnails">
                        {% for address in addresslist %}

                            <li class="user-addresslist {% if address.isdefault %}defaultAddr {% endif %} ">
                                <span class="new-option-r"><i class="am-icon-check-circle"></i>默认地址</span>
                                <p class="new-tit new-p-re">
                                    <span class="new-txt">{{ address.aname }}</span>
                                    <span class="new-txt-rd2">{{ address.aphone }}</span>
                                </p>
                                <div class="new-mu_l2a new-p-re">
                                    <p class="new-mu_l2cw">
                                        <span>地址：<span class="addr">{{ address.addr }}</span></span>

                                </div>
                                <div class="new-addr-btn">
                                    <a href="#"><i class="am-icon-edit"></i>编辑</a>
                                    <span class="new-addr-bar">|</span>
                                    <a href="javascript:void(0);" onclick="delClick(this);"><i
                                            class="am-icon-trash"></i>删除</a>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                    <div class="clear"></div>
                    <a class="new-abtn-type" data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0}">添加新地址</a>
                    <!--例子-->
                    <div class="" id="doc-modal-1">

                        <div class="add-dress">

                            <!--标题 -->
                            <div class="am-cf am-padding">
                                <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">新增地址</strong> /
                                    <small>Add&nbsp;address</small></div>
                            </div>
                            <hr>

                            <div class="am-u-md-12 am-u-lg-8" style="margin-top: 20px;">
                                <form class="am-form am-form-horizontal" id="frm" method="post"
                                      href="{% url 'user:address' %}">
                                    {% csrf_token %}
                                    <div class="am-form-group">
                                        <label for="user-name" class="am-form-label">收货人</label>
                                        <div class="am-form-content">
                                            <input type="text" id="user-name" name="aname" placeholder="收货人">
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="user-phone" class="am-form-label">手机号码</label>
                                        <div class="am-form-content">
                                            <input id="user-phone" placeholder="手机号必填" name="aphone" type="email">
                                        </div>
                                    </div>
                                    <div class="am-form-group">
                                        <label for="user-address" class="am-form-label">所在地</label>
                                        <div class="am-form-content address">
                                            <select id="province" onchange="loadCity();">
                                                <option value="a">浙江省</option>
                                                <option value="b" selected="">湖北省</option>
                                            </select>
                                            <select id="city" onchange="loadTown();">
                                                <option value="a">温州市</option>
                                                <option value="b" selected="">武汉市</option>
                                            </select>
                                            <select id="town">
                                                <option value="a">瑞安区</option>
                                                <option value="b" selected="">洪山区</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="user-intro" class="am-form-label">详细地址</label>
                                        <div class="am-form-content">
                                            <textarea name="addr" onfocus="fillcontent(this)" class="" rows="3"
                                                      id="user-intro" placeholder="输入详细地址"></textarea>
                                            <small>100字以内写出你的详细地址...</small>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <div class="am-u-sm-9 am-u-sm-push-3">
                                            <a class="am-btn am-btn-danger" onclick="$('#frm').submit()">保存</a>
                                            <a href="javascript: void(0)" class="am-close am-btn am-btn-danger"
                                               data-am-modal-close="">取消</a>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>

                    </div>

                </div>

                <script type="text/javascript">
                    $(document).ready(function () {
                        $(".new-option-r").click(function () {
                            $(this).parent('.user-addresslist').addClass("defaultAddr").siblings().removeClass("defaultAddr");
                            var addr = $(this).parent('.user-addresslist').find('span.addr').text();
                            {#alert(addr);#}
                            {#$.get('/user/loadarea/', {'pid': pid}, function (result) {#}
                            $.get('/user/setdefaultaddr/', {'addr': addr}, function (result) {
                                console.log(result.msg)
                            });
                        });

                        var $ww = $(window).width();
                        if ($ww > 640) {
                            $("#doc-modal-1").removeClass("am-modal am-modal-no-btn")
                        }

                    })
                </script>

                <div class="clear"></div>

            </div>

        </div>
    </div>



{% endblock %}


{% block footerjs %}


    <script>

        $('.logout').click(function () {

            $.ajax({
                type: 'post',
                url: '/user/logout/',
                data: 'csrfmiddlewaretoken=' + $('input[name="csrfmiddlewaretoken"]').val(),
                success: function (result) {


                    if (result.delflag) {
                        window.location.href = '/user/login/'
                    }

                }
            })
        })

        function fillcontent(textaraObj) {
            var pro = $('#province option:selected').text()
            var city = $('#city option:selected').text()
            var town = $('#town option:selected').text()

            // 拼接成完整地址
            $(textaraObj).val(pro + ' ' + city + ' ' + town)
        }

        // 删除地址
        function delClick(obj) {
            var addr = $(obj).parent().parent('.user-addresslist').find('span.addr').text();
            var press = confirm('是否要删除该地址： ' + addr)
            if (press == true) {
                $.get('/user/deleteaddr/', {'addr': addr}, function (result) {
                    console.log(result)
                });
                $(obj).parent().parent('.user-addresslist').remove();
            }
        }

    </script>


{% endblock %}

userapp/templates/center.html
{% extends 'base.html' %}

{% block title %}用户中心{% endblock %}

{% block main %}

    
    <div class="Bott">
			<div class="wrapper clearfix" style="margin: 0 auto">
				<div class="zuo fl" style="margin-left: 100px">
					<h3>
						<a href="/"><img src="/static/tx.png"></a>
						<p class="clearfix"><span class="fl">[{{ suser.uname }}]</span><span class="fr logout">[退出登录]</span></p>
					</h3>
					<div>
						<ul>
							<li><a href="http://127.0.0.1:8000/user/center/#">我的订单</a></li>
						</ul>
						<ul>
							<li><a href="/user/address/">地址管理</a></li>
						</ul>
                        <ul>
							<li><a href="/">回到首页</a></li>
						</ul>

					</div>
				</div>
				<div class="you fl">

    <div class="tx clearfix">
						<div class="fl clearfix">
							<a href="/user/center/" class="fl"><img src="/static/tx.png"></a>
							<p class="fl"><span>{{ suser.uname }}</span><a href="http://127.0.0.1:8000/user/usercenter/#">修改个人信息&gt;</a></p>
						</div>
						<div class="fr">绑定邮箱：12****4@**.com</div>
					</div>
    <div class="bott">
						<div class="clearfix">
							<a href="http://127.0.0.1:8000/user/usercenter/#" class="fl"><img src="/static/gxin1.jpg"></a>
							<p class="fl"><span>待支付的订单：<strong>0</strong></span>
								<a href="http://127.0.0.1:8000/user/usercenter/#">查看待支付订单&gt;</a>
							</p>
						</div>
						<div class="clearfix">
							<a href="http://127.0.0.1:8000/user/usercenter/#" class="fl"><img src="/static/gxin2.jpg"></a>
							<p class="fl"><span>待收货的订单：<strong>0</strong></span>
								<a href="http://127.0.0.1:8000/user/usercenter/#">查看待收货订单&gt;</a>
							</p>
						</div>
					</div>

				</div>

            </div>
            </div>
    {% csrf_token %}


{% endblock %}


{% block footerjs %}
    
    
    <script>
    
        $('.logout').click(function () {

            $.ajax({
                type:'post',
                url:'/user/logout/',
                data:'csrfmiddlewaretoken='+$('input[name="csrfmiddlewaretoken"]').val(),
                success:function(results){
                    if(results.delflag){
                        window.location.href='/'
                    }

                }
            })
        })
    
    </script>


{% endblock %}

userapp/templates/login.html
{% extends 'base.html' %}

{% block title %}
用户登录页面
{% endblock %}


{% block headerjs %}

    <script type="text/javascript" src="/static/md5-min.js"></script>
    <style type="text/css">
        #id_captcha_1{
            height: 36px;
            width: 100px;
        }
    </style>

{% endblock %}


{% block main %}


     <div class="login-body">
        <div class="login-card">
            <div class="login-top">
                <h3>新用户登录</h3>
                <h5>尊敬的用户，欢迎您回来！</h5>
            </div>
            <div class="login-bottom">
               <form method="post" action="{% url 'user:login' %}" onsubmit="return login();">
                   <input type="hidden" name="time" id="time">
                    <div class="login-input-box">
                        {% csrf_token %}
                    <input type="text" id="uname" name="uname" value="" class="login-admin active" placeholder="邮箱登录" minlength="4" maxlength="15">{{ msg }}

                    <span style="color:red;" id="aSpan"></span>

                        <input type="password" id="pwd" name="pwd" value="" class="login-password" required minlength="4">
                        <span style="color:red;" id="pSpan"></span>

                        {#                    <input type="text" style="height:36px;width: 100px;" id="code" onblur="checkCode(this.value)">{{ form.captcha }}<span style="color:red;" id="cSpan"></span>#}
                        {{ form.captcha }} <span>{{ validata.captcha.errors.0 }}</span><br>
                        <input type="hidden" name="redirect" value="">
                        <input type="hidden" name="cartitems" value="None">
                        <input type="hidden" id="next" name = "next" value="{{ next }}">
                        <button class="login-btn" style="color: white;text-decoration: none;cursor: pointer">登录</button>
                         <a href="{% url 'user:register' %}">注册</a>
                </div>
               </form>
                <div class="login-img">
                    <img src="/static/login_05.png" alt="">
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block footerjs %}
    <script src="https://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
    <script>


        function login(){
            //获取输入框的值
            var password = $('#pwd').val();
            var hex_pwd = hex_md5(password);
            //var hex_pwd = hex_md5(password+time)
            $('#pwd').val(hex_pwd);

        }

        //点击刷新验证码
        $(function () {
            $('.captcha').css({
                'cursor': 'pointer'
            });
            // ajax刷新
            $('.captcha').click(function () {
                console.log('click');
                $.get("{% url 'captcha-refresh' %}",
                    function (result) {
                        $('.captcha').attr('src', result['image_url']);
                        $('#id_captcha_0').val(result['key'])
                    }
                );
            });
        })

    </script>

{% endblock %}

userapp/templates/register.html
{% extends 'base.html' %}

{% block title %}注册页面{% endblock %}


{% block headerjs %}
    <script type="text/javascript" src="/static/md5-min.js"></script>
{% endblock %}


{% block main %}

     <div class="login-body">
        <div class="login-card">
            <div class="login-top">
                <h3>新用户注册</h3>
                <h5>尊敬的用户，欢迎您回来！</h5>
            </div>
            <div class="login-bottom">
               <form method="post" action="/user/register/" onsubmit="return register();">
                    <div class="login-input-box">
                        {% csrf_token %}

                    <input type="text" id="uname" name="uname" value="" onblur="checkUname(this.value)" class="login-admin active" placeholder="邮箱注册">
                    <span style="color:red;" id="aSpan"></span>

                    <input type="password" id="pwd" name="pwd" value="" class="login-password">
                    <span style="color:red;" id="pSpan"></span>

                    <button class="login-btn" style="color: white;text-decoration: none;cursor: pointer">注册</button>
                </div>
               </form>
                <div class="login-img">
                    <img src="/static/login_05.png" alt="">
                </div>
            </div>
        </div>
    </div>



{% endblock %}


{% block footerjs %}



    <script>
        function isEmail(str){
            var reg = /^[a-zA-Z0-9_-]{6,}@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/;
            return reg.test(str);
        }

        //用户名唯一校验
        function checkUname(username){
            var flag = false;
            $.ajax({
                url:'/user/checkuname/',
                type:'GET',
                async:false,
                data:{'uname':username},
                success:function(result){
                    var cflag = result.flag;
                    if(cflag){
                       flag = true;
                       $('#aSpan').html('用户名已存在！')
                    }
                }


            });

            return flag;
        }




        function register(){
            //获取输入框的值
            var account = $('#uname').val();
            var password = $('#pwd').val();

            //简单校验
            if(account.length<6||!isEmail(account)||checkUname(account)){
                $('#aSpan').text('邮箱长度不能小于六位');
                return false;
            }

            if(password.length<6){
                $('#pSpan').text('密码长度不能小于六位');
                return false;
            }

            //将密码框内容进行md5加密
            var hex_pwd = hex_md5(password);
            $('#pwd').val(hex_pwd);

            return true;



        }


    </script>


{% endblock %}