cart/urls.py
#coding=utf-8

from django.contrib import admin
from django.urls import path, re_path, include
import goods
from cart import views
from netshop.settings import DEBUG, MEDIA_ROOT

app_name = 'cart'

urlpatterns = [
    path('addcart/', views.AddCartView.as_view(), name='addcart'),
    path('gocart/', views.GoCartView.as_view(), name='gocart'),


]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

netshop/urls.py
#coding=utf-8
"""netshop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

import goods
from netshop.settings import DEBUG, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls')),
    path('user/', include('userapp.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('test/', include('testapp.urls')),
    path('captcha/', include('captcha.urls')),      # 验证码路由配置
]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

userapp/urls.py
#coding=utf-8

from django.contrib import admin
from django.urls import path, re_path, include
import goods
from userapp import views
from netshop.settings import DEBUG, MEDIA_ROOT

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('checkuname/', views.CheckUsername.as_view(), name='checkuname'),
    path('center/', views.CenterView.as_view(), name='center'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('refresh/', views.refresh, name='refresh'),       # 刷新验证码
    path('address/', views.AddressView.as_view(), name='address'),
    path('loadarea/', views.LoadAreaView.as_view(), name='loadarea'),
    path('setdefaultaddr/', views.SetDefaultAddrView.as_view(), name='setdefaultaddr'),
    path('deleteaddr/', views.DeleteAddrView.as_view(), name='deleteaddr'),

]

if DEBUG:
    from django.views.static import serve
    urlpatterns.append(re_path(r'media/(.*)', serve, kwargs={'document_root': MEDIA_ROOT}))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>{% block title %}title{% endblock %}</title>
    <link rel="stylesheet" href="/static/login.css">
    <link rel="stylesheet" href="/static/index.css">
    <link rel="stylesheet" href="/static/detail.css">
    <link rel="stylesheet" href="/static/carts.css">
    <link rel="stylesheet" href="/static/reset.css">
    <link rel="stylesheet" href="/static/mygxin.css">
    <script src="/static/jquery.min.js"></script>
    <script src="/static/carts.js"></script>

    {% block headerjs %}

    {% endblock %}


</head>

<body>

<div class="head">
    <div class="head-in">
        <ul class="options">
            <li class="sub"><a href="http://127.0.0.1:8000/?category=2#">我的订单</a></li>

            <li class="sub"><a href="http://127.0.0.1:8000/?category=2#">客户服务</a></li>
            <li class="sub"><a href="{% url 'cart:gocart' %}">我的购物车</a></li>
        </ul>

        {% if suser %}
            <div class="sign"><a href="{% url 'user:logout' %}">退出登录</a></div>
            <div class="register">welcome, <a href="{% url 'user:center' %}">{{ suser.uname }}</a></div>
        {% else %}
            <div class="register"><a href="{% url 'user:register' %}">免费注册</a></div>
            <div class="sign"><a href="{% url 'user:login' %}?next={{ request.path }}">登录</a></div>
        {% endif %}


    </div>
</div>
<div class="search">
    <ul class="items">
        <li class="item">
            <a href="http://127.0.0.1:8000/?category=2#">
                <img src="/static/1_09.png">
                <p>10:00开抢</p>
            </a>
        </li>
        <li class="item">
            <a href="http://127.0.0.1:8000/?category=2#">
                <img src="/static/1_11.png">
                <p>买手砍价</p>
            </a>
        </li>
        <li class="item">
            <a href="http://127.0.0.1:8000/?category=2#">
                <img src="/static/1_13.png">
                <p>验货质检</p>
            </a>
        </li>
    </ul>
    <div class="input">
        <input type="" name="" value="请输入想找的宝贝">
        <img src="/static/1_06.png">
    </div>
</div>


{% block main %}

{% endblock %}


{% block footerjs %}

{% endblock %}


</body>

</html>